instagram/sms/urls.py
from django.conf.urls import url

from . import apis

urlpatterns = [
    url(r'^send-sms/$', apis.SendSMS.as_view(), name='sms-send')
]

instagram/post/models.py
from django.db import models
from django.conf import settings


class HasAuthorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(author__isnull=False)


class Post(models.Model):
    objects = HasAuthorManager()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    photo = models.ImageField(upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.photo.name.split('post/')[-1]

    @property
    def total_likes(self):
        return self.liked_users.count()

    class Meta:
        ordering = ['-created_at']


class PostComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

instagram/post/forms.py
from django import forms

from .models import Post, PostComment


class PostForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['author'].required = True

    # photo = forms.ImageField(required=True)
    # # Text를 받을 수 있는 field 추가
    # text = forms.CharField(max_length=5)
    class Meta:
        model = Post
        fields = (
            'photo',
        )

    def save(self, commit=True, *args, **kwargs):
        # 1. 처음으로 Post객체가 만들어지는 순간
        # 2. instance의 author필드가 비어있으면 save(commit=True)를 비허용
        #   2-1. 하지만 save(commit=False)는 허용 (나중에 author필드를 채움
        # 3. save()에 author키워드 인수값을 전달할 수 있도록 save()메서드를 재정의

        # 새로 저장하려는 객체이다(pk값이 없음
        # form.save(author=request.user)

        # # 새로 저장하려는 객체이며(pk값이 없음), DB에 바로 저장하려고 할 경우(commit=True)
        # if not self.instance.pk and commit:
        #     # author값을 키워드인수 묶음에서 pop으로 삭제하며 값을 가져온다.
        #     author = kwargs.pop('author', None)
        #     # author값이 없을 경우 (키워드가 없었거나 값이 주어지지 않은 경우)
        #     if not author:
        #         # valueError를 발생시
        #         raise ValueError('Author field is required')
        #     # author값이 존재하면 자신의 instance의 author필드값을 채움
        #     self.instance.author = author
        # # 슈퍼클래스의 save를 호출
        # return super().save(*args, **kwargs)

        if not self.instance.pk and commit:
            raise ValueError('PostForm commit=True save() is not allowed')
        return super().save(*args, **kwargs)


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['content']

instagram/post/urls/views.py
from django.conf.urls import url

from ..views.comment import (

    post_comment_create,
    post_comment_delete,

)
from .. import views

app_name = 'post'

urlpatterns = [
    url(r'^$', views.post_list, name='list'),  # /post
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='detail'),  # /post/1
    url(r'^create/$', views.post_create, name='create'),  # /post/create/
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='delete'),  # /post/1/delete
    url(r'^like/$', views.post_like, name='like'),  # /post/like
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.post_comment_create, name='comment_create'),  # /post/1/comment/create
    url(r'^(?P<pk>\d+)/comment/delete/$', views.post_comment_delete, name='comment_delete'),  # /post/1/comment/delete
]

instagram/post/views.py
"""
post_list뷰를 'post/' URL에 할당
"""
# from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import Post, PostComment
from .forms import PostForm, PostCommentForm
from .decorators import login_required


def post_list(request):
    """
    모든 Post목록을 리턴
    template은 'post/post_list.html'을 사용
    :param request:
    :return:
    """
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    comment_form = PostCommentForm()
    context = {
        'post': post,
    }
    return render(request, 'post/post_detail.html', context)

@login_required
def post_create(request):
    """
    HTTP GET: Post를 생성하는 빈 form을 보여주기
    HTTP POST: Post 생성하기

    1. 이 뷰에 접근할 때 해당 사용자가 인증된 상태가 아니면 로그인 뷰로 redirect
    2. form.is_valid()를 통과한 후 생성하는 Post객체에 author 정보를 추가하기
    :param request:
    :return:
    """
    # if not request.user.is_authenticated:
    #     return redirect('member:login')

    if request.method == "POST":
        # POST 요청의 경우 PostForm 인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # form 생성과정에서 전달된 데이터들이 Form의 모든 field들에 유효한지 검사
        if form.is_valid():
            # 유효할 경우 Post인스턴스 생성 및 저장
            # 1. 커스텀 메서드 사용
            # form.save(author=request.user)

            # 2. 기존 Django의 ModelForm방식 사용
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:list')
        # form의 field가 하나라도 유효하지 않은 경우
        else:
            print('Form is invalid!')

    # GET 요청에선 이부분이 무조건 실행
    # POST요청에선 form.is_valid()를통과하지 못하면 이부분이 실행
    else:
        form = PostForm()

    context = {
        'form': form
    }
    return render(request, 'post/post_form.html', context)


def post_delete(request, pk):
    """
    HTTP POST: Post 삭제하기
    :param request:
    :return:
    """
    # if not request.user.is_authenticated:
    #     return redirect('post:list')

    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        if post.author == request.user:
            post.delete()
            next = request.GET.get('next', '').strip()
            if next:
                return redirect(next)
        else:
            raise PermissionDenied('작성자가 아닙니다')


@login_required
def post_like(request):
    # user = request.user
    # if not user.is_authenticated:
    #     return HttpResponse(status=403)

    if request.method == "POST":
        user = request.user
        pk = request.POST.get('pk')
        post = get_object_or_404(Post, pk=pk)
        # 만약 user가 like 하지 않은 post라면, like 하기
        if not user.has_liked_post(post):
            user.like_post(post)
        # 만약 user가 이미 like 한 post라면, like 취소
        else:
            user.dislike_post(post)

        context = {
            'like_count': post.total_likes
        }
        return HttpResponse(json.dumps(context), content_type="application/json")


def post_comment_create(request, post_pk):
    """
    HTTP POST: PostComment 생성하기
    로그인한 유저만 요청 가능하도록 함
    작성하는 Comment에 author정보 추가

    :param request:
    :return:
    """
    if not request.user.is_authenticated:
        return redirect('member:login')

    post = get_object_or_404(Post, pk=post_pk)
    if request.method == "POST":
        form = PostCommentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.post = post
            instance.author = request.user
            instance.save()
            # GET parameter로 next 값이 전달되면
            # 다음에 갈 URL (next)가 빈 문자열이 아닌 경우
            next = request.GET.get('next', '').strip()
            print(next)
            if next:
                return redirect(next)

    return redirect('post:list')


def post_comment_delete(request, pk):
    """
    HTTP POST: PostCommet 삭제하기
    :param request:
    :return:
    """
    if request.method == "POST":
        comment = get_object_or_404(PostComment, pk=pk)
        if comment.author == request.user:
            comment.delete()
            next = request.GET.get('next', '').strip()
            if next:
                return redirect(next)
        else:
            raise PermissionDenied('작성자가 아닙니다')

    return redirect('post:list')

instagram/post/views/comment.py
"""
post_list뷰를 'post/' URL에 할당
"""
# from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404

from ..forms import PostCommentForm
from ..models import Post, PostComment


__all__ = (
    'post_comment_create',
    'post_comment_delete',
)


def post_comment_create(request, post_pk):
    """
    HTTP POST: PostComment 생성하기
    로그인한 유저만 요청 가능하도록 함
    작성하는 Comment에 author정보 추가

    :param request:
    :return:
    """
    if not request.user.is_authenticated:
        return redirect('member:login')

    post = get_object_or_404(Post, pk=post_pk)
    if request.method == "POST":
        form = PostCommentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.post = post
            instance.author = request.user
            instance.save()
            # GET parameter로 next 값이 전달되면
            # 다음에 갈 URL (next)가 빈 문자열이 아닌 경우
            next = request.GET.get('next', '').strip()
            print(next)
            if next:
                return redirect(next)

    return redirect('post:list')


def post_comment_delete(request, pk):
    """
    HTTP POST: PostCommet 삭제하기
    :param request:
    :return:
    """
    if request.method == "POST":
        comment = get_object_or_404(PostComment, pk=pk)
        if comment.author == request.user:
            comment.delete()
            next = request.GET.get('next', '').strip()
            if next:
                return redirect(next)
        else:
            raise PermissionDenied('작성자가 아닙니다')

    return redirect('post:list')

instagram/post/views/post.py
"""
post_list뷰를 'post/' URL에 할당
"""
# from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from ..models import Post, PostComment
from ..forms import PostForm, PostCommentForm
from ..decorators import login_required

__all__ = (
    'post_list',
    'post_detail',
    'post_create',
    'post_delete',
    'post_like',
)

def post_list(request):
    """
    모든 Post목록을 리턴
    template은 'post/post_list.html'을 사용
    :param request:
    :return:
    """
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    comment_form = PostCommentForm()
    context = {
        'post': post,
    }
    return render(request, 'post/post_detail.html', context)

@login_required
def post_create(request):
    """
    HTTP GET: Post를 생성하는 빈 form을 보여주기
    HTTP POST: Post 생성하기

    1. 이 뷰에 접근할 때 해당 사용자가 인증된 상태가 아니면 로그인 뷰로 redirect
    2. form.is_valid()를 통과한 후 생성하는 Post객체에 author 정보를 추가하기
    :param request:
    :return:
    """
    # if not request.user.is_authenticated:
    #     return redirect('member:login')

    if request.method == "POST":
        # POST 요청의 경우 PostForm 인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # form 생성과정에서 전달된 데이터들이 Form의 모든 field들에 유효한지 검사
        if form.is_valid():
            # 유효할 경우 Post인스턴스 생성 및 저장
            # 1. 커스텀 메서드 사용
            # form.save(author=request.user)

            # 2. 기존 Django의 ModelForm방식 사용
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:list')
        # form의 field가 하나라도 유효하지 않은 경우
        else:
            print('Form is invalid!')

    # GET 요청에선 이부분이 무조건 실행
    # POST요청에선 form.is_valid()를통과하지 못하면 이부분이 실행
    else:
        form = PostForm()

    context = {
        'form': form
    }
    return render(request, 'post/post_form.html', context)


def post_delete(request, pk):
    """
    HTTP POST: Post 삭제하기
    :param request:
    :return:
    """
    # if not request.user.is_authenticated:
    #     return redirect('post:list')

    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        if post.author == request.user:
            post.delete()
            next = request.GET.get('next', '').strip()
            if next:
                return redirect(next)
        else:
            raise PermissionDenied('작성자가 아닙니다')


@login_required
def post_like(request):
    # user = request.user
    # if not user.is_authenticated:
    #     return HttpResponse(status=403)

    if request.method == "POST":
        user = request.user
        pk = request.POST.get('pk')
        post = get_object_or_404(Post, pk=pk)
        # 만약 user가 like 하지 않은 post라면, like 하기
        if not user.has_liked_post(post):
            user.like_post(post)
        # 만약 user가 이미 like 한 post라면, like 취소
        else:
            user.dislike_post(post)

        context = {
            'like_count': post.total_likes
        }
        return HttpResponse(json.dumps(context), content_type="application/json")

instagram/templates/post/post_detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'include/post.html' with post_type='detail' %}
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script>
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script>

var heart = $('.heart')

// 하트 클릭 시,
heart.click(function() {
    // 색깔 채워넣기/비우기
    $(this).toggleClass("fa-heart-o fa-heart")

    // 해당 post pk 가져오기
    var pk = $(this).attr('name')

    // ajax post reqeust 보내기
    $.ajax({
        type: "POST",
        url: "{% url 'post:like' %}",
        data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function(response){
            var totalLikeEl = $('#' + pk + '-total-likes');
            var totalLikeNum = totalLikeEl.text()
            totalLikeEl.html('좋아요 수: ' + response.like_count)
        },
        error: function(response){
            alert("로그인이 필요합니다.");
            window.location.replace("/member/login/")

        }
    });
})

</script>
{% endblock %}

instagram/templates/post/post_form.html
{% extends 'base.html' %}

{% block content %}
<!--{% if form.errors.non_field_errors %}-->
<!--{{ form.errors.non_field_errors }}-->
<!--{% endif %}-->
<span>업로드할 사진을 선택해주세요.</span>
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

instagram/templates/post/post_list.html
<!--Template language의 for구문을 사용해서 각 Post의 photo항목을 출력 (O)-->
<!--.photo속성의 'url'속성을 사용해서 img태그를 사용 실제 이미지를 보여주기 (O)-->

<!--1. 사진 업로드하기 (O)-->
<!--2. 사진에 댓글달기 (O)-->
<!--extra1) urls.py모듈을 post애플리케이션 내부에 생성하고,
    include를 이용해서 root urls.py모듈에서 사용 (O)-->
<!--extra2) 사진 댓글 지우기, 사진 지우기 (O)-->


<!--
1. 작성자 username나오게
2. Post를 나타내는 HTML요소를 include/post.html로 분리해서 사용
3. Post 및 Comment삭제 기능 추가(작성한 유저만 가능하도록)
-->

<!--1. post를 작성한 작성자(author)의 username을 template에서 표시하도록 만들기-->
<!--2. post를 나타내는 HTML 요소를 include/post.html로 분리해서 post_list, post_detail에서 include 하여 나타내기-->
<!--3. post와 comment를 삭제할 수 있는 기능 추가 (해당 post나 comment의 작성자인 경우에만 삭제가 가능하도록 하기)-->

{% extends 'base.html' %}
{% block content %}
{% for post in posts %}
{% include 'include/post.html' with post_type='list'  %}
{% endfor %}
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script>

var heart = $('.heart')

// 하트 클릭 시,
heart.click(function() {
    // 색깔 채워넣기/비우기
    $(this).toggleClass("fa-heart-o fa-heart")

    // 해당 post pk 가져오기
    var pk = $(this).attr('name')

    // ajax post reqeust 보내기
    $.ajax({
        type: "POST",
        url: "{% url 'post:like' %}",
        data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function(response){
            var totalLikeEl = $('#' + pk + '-total-likes');
            var totalLikeNum = totalLikeEl.text()
            totalLikeEl.html('좋아요 수: ' + response.like_count)
        },
        error: function(response, url){
            alert("로그인이 필요합니다.");
            console.log(response)
            window.location.replace("/member/login/")

        }
    });
})


</script>
{% endblock %}