instagram/sms/urls.py
from django.conf.urls import url

from . import apis

urlpatterns = [
    url(r'^send-sms/$', apis.SendSMS.as_view(), name='sms-send')
]

instagram/member/urls/views.py
from django.conf.urls import url

from ..views.auth import signup, login, logout
from ..views.auth_facebook import facebook_login, FrontFacebookLogin

app_name = 'member'

urlpatterns = [
    url(r'^signup/$', signup, name='signup'),  # member/signup/
    url(r'^login/$', login, name='login'),  # member/login/
    url(r'^logout/$', logout, name='logout'),  # member/logout/
    url(r'^facebook-login/$', facebook_login, name='facebook-login'),  # member/facebook-login/
    url(r'^front-facebook-login/$', FrontFacebookLogin.as_view(), name='front-facebook-login'),
    # member/front-facebook-login/
]

instagram/post/urls/views.py
from django.conf.urls import url

from ..views.comment import (

    post_comment_create,
    post_comment_delete,

)
from .. import views

app_name = 'post'

urlpatterns = [
    url(r'^$', views.post_list, name='list'),  # /post
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='detail'),  # /post/1
    url(r'^create/$', views.post_create, name='create'),  # /post/create/
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='delete'),  # /post/1/delete
    url(r'^like/$', views.post_like, name='like'),  # /post/like
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.post_comment_create, name='comment_create'),  # /post/1/comment/create
    url(r'^(?P<pk>\d+)/comment/delete/$', views.post_comment_delete, name='comment_delete'),  # /post/1/comment/delete
]

instagram/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram</title>
    <script src="https://use.fontawesome.com/e00a1690f1.js"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
</head>
<body>
<h1><a href="{% url 'post:list' %}">Instagram</a></h1>
<p>
    <p><a href="{% url 'post:create' %}">글 쓰기</a></p>
    {% if user.is_authenticated %}
    <p>{{ user }} 님, 환영합니다!</p>
    <p><a href="{% url 'member:logout' %}">로그아웃</a></p>
    {% else %}
    <a href="{% url 'member:login' %}">로그인</a>
    {% endif %}
</p>
<hr>
{% block content %}
{% endblock %}
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="{% static 'js/post.js' %}"></script>
</body>
</html>